### ISSUE TITLE
Please clarify what the purpose of this is

### ISSUE THREAD

**Issue by maskedvillain** [lencx/nofwl#1]
Sorry i'm just unclear what this is, what to do with it in ChatGPT, and how to run / install / make use of it in any way. Please update readme

**Comment by Theblackcat98** [comment]
> Sorry i'm just unclear what this is, what to do with it in ChatGPT, and how to run / install / make use of it in any way. Please update readme

As the readme clearly states: "Currently under active development, please be patient. Its development is inspired by [lencx/ChatGPT](https://github.com/lencx/ChatGPT), but NoFWL has more powerful features."
It is under active development, the dev asks to be PATIENT, and they also explain that it's another version of their ChatGPT app with more powerful feature.

As of now, you can't "run / install / make use of it in any way", unless you just start reading source code and help in development that way.

Cheers

**Comment by yixinBC** [comment]
> is it another desktop app for chatgpt? any difference with lencx/chatgpt?

curruntly nobody but @lencx konw☺️

**Comment by myndxero** [comment]
stuff.

**Comment by lencx** [comment]
preview: https://twitter.com/lencx_/status/1637055720410730497

**Comment by lencx** [comment]
> Except it's not in active development at all. This is a hello world application at this point with over 500 stars. Makes me wonder what the philosophy behind this is. The way the "answers" are written on this issue does not inspire confidence.

Its core code is developed in closed-source mode, and this repository will be used in the future to distribute installers and build its plugin ecosystem (it doesn't seem sensible to draw such an easy conclusion).

**Comment by benhot** [comment]
waitlist

**Comment by ThePhoenixBird** [comment]
# _"Its core code is developed in closed-source mode"_ 

Why??

**Comment by lencx** [comment]
> # _"Its core code is developed in closed-source mode"_
> Why??

- The previously open-sourced ChatGPT desktop application has been used by hackers to spread malware. It can be easily built by anyone, and once it falls into the wrong hands, it can be a terrifying thing.
- I want to create an AI tool platform that includes many free features (with far more planned features than the existing ChatGPT desktop application) and subscription-based features.
- Many people with ulterior motives are commercializing my open-source project, and they may even delete all information related to me.

**Comment by vrozkovec** [comment]
Worth mentioning this issue that explains some reasoning behind nofwl: https://github.com/lencx/ChatGPT/issues/477

**Comment by ThePhoenixBird** [comment]
> > # _"Its core code is developed in closed-source mode"_
> > Why??
> 
>     * The previously open-sourced ChatGPT desktop application has been used by hackers to spread malware. It can be easily built by anyone, and once it falls into the wrong hands, it can be a terrifying thing.
> 
>     * I want to create an AI tool platform that includes many free features (with far more planned features than the existing ChatGPT desktop application) and subscription-based features.
> 
>     * Many people with ulterior motives are commercializing my open-source project, and they may even delete all information related to me.

1. That is an issue that has no relation to the software itself, all kinds of applications can suffer from this problem, Closed-Source apps have suffered from Trojans and viruses since the beginning of the internet, because people will always look for cracks or hacks to bypass restrictions to access it. Open-Source has also suffered from this problem when compiled binaries were served through 3rd parties, or people downloaded code, ISOS, and binaries from unknown sources. **The first thing that any Open-Source project tells to its community is to only download from their official repo.**

2.  That's fine, just leave the non-subscription-based features code into this repo as Open-Source and write the rest as Closed-Source behind doors. I wouldn't trust my OpenAI API key to a software that I cant read what it does, the billing costs of an error or a misuse of the API could be astronomic.

3. GPLv3.0 licenses do not forbid commercializing the code, modifying it, or releasing it with or without modifications, anyone can fork it, that is the pure essence of open-source. It is unfortunate and I condemn people who remove the attribution from your code which is mandatory per GPLv3.0 https://opensource.stackexchange.com/questions/4577/does-gplv3-require-attribution, and do evil things with it, but that shouldn't be a reason to take the project closed doors. The more the community grows around your project you will find more collaborators to help you out with it.

**Comment by lencx** [comment]
> 2\. That's fine, just leave the non-subscription-based features code into this repo as Open-Source and write the rest as Closed-Source behind doors. I wouldn't trust my OpenAI API key to a software that I cant read what it does, the billing costs of an error or a misuse of the API could be astronomic.

Respect your decision. If you think it's not safe, just don't install it. I never force anyone. Currently, ChatGPT is closed source, and many applications developed using OpenAI API are also closed source. If you are a programmer, I believe you can monitor all your outbound traffic instead of speculating here.

**Comment by cobblepot1** [comment]
"Respect your decision. If you think it's not safe, just don't install it. I never force anyone. Currently, ChatGPT is closed source, and many applications developed using OpenAI API are also closed source."

Appreciate you being straightforward. I won't install it. Public registered companies subject to regulation, liability, and courts are much safer bets than closed-source by an anonymous username. I'm amazed that people are comfortable installing this. Anyone who knows of an open-source alternative, please let us know. Thanks.

**Comment by lisiur** [comment]
> "Respect your decision. If you think it's not safe, just don't install it. I never force anyone. Currently, ChatGPT is closed source, and many applications developed using OpenAI API are also closed source."
> 
> 
> 
> Appreciate you being straightforward. I won't install it. Public registered companies subject to regulation, liability, and courts are much safer bets than closed-source by an anonymous username. I'm amazed that people are comfortable installing this. Anyone who knows of an open-source alternative, please let us know. Thanks.

check this [ChatWizard](https://github.com/lisiur/ChatWizard)

**Comment by Ryangr0** [comment]
Not making this open source is a mistake. Think about it. You have an opportunity here. I don't think I can think of any reason why this would need to be closed off unless you're thinking about making money already?

**Comment by Rockincowboy** [comment]
I just recently found out about AI. I was wandering when money would become the priority. I guess we found out. And that is how it will end up in the wrong hands. I predict more viruses and trojans. why fix what isn't broken?
